In [2]:
import pandas as pd
import numpy as np

liaison_pre=pd.read_csv('/Users/humphreyshen/Desktop/2021 Database Project/班級聯絡人/班級聯絡人-總表.csv')
liaison_preselect=liaison_pre.iloc[:,0:11]
liaison_select=liaison_preselect.dropna(subset=['校友編號'])
liaison_select.head()

,序號,校友編號,畢業年,科系,班級,姓名,聯絡電話,信箱,可觸及人數,生日,liaison
0,1.0,AD05352108,53,會計,A,王小佗,0910128383,hsiaoto@gmail.com,15,NaN,1.0
1,2.0,AD05552122,55,會計,A,陳秀男,0979610770,willchen65@yahoo.com.tw,0,NaN,1.0
3,4.0,AD05921106,59,英文,不分班,曾文欽,0930756966,Charlestw@mail2000.com.tw,NaN,NaN,1.0
4,5.0,AD05941107,59,法律,A,洪長岸,0905516878,monty@highlink.com.tw(錯誤),26,1946/1/18,1.0
5,6.0,AD05952177,59,會計,A,蕭如意,0937894952,louis668@ms43.hinet.net,100,NaN,1.0

In [3]:
liaison_select_rename=liaison_select.rename({'序號':'id','校友編號':'alumni_id','畢業年':'grad_year','科系':'dept','班級':'class','姓名':'zh_name','聯絡電話':'cell','信箱':'email','可觸及人數':'contact','生日':'birthday'}, axis=1)
liaison_select_rename.head()

,id,alumni_id,grad_year,dept,class,zh_name,cell,email,contact,birthday,liaison
0,1.0,AD05352108,53,會計,A,王小佗,0910128383,hsiaoto@gmail.com,15,NaN,1.0
1,2.0,AD05552122,55,會計,A,陳秀男,0979610770,willchen65@yahoo.com.tw,0,NaN,1.0
3,4.0,AD05921106,59,英文,不分班,曾文欽,0930756966,Charlestw@mail2000.com.tw,NaN,NaN,1.0
4,5.0,AD05941107,59,法律,A,洪長岸,0905516878,monty@highlink.com.tw(錯誤),26,1946/1/18,1.0
5,6.0,AD05952177,59,會計,A,蕭如意,0937894952,louis668@ms43.hinet.net,100,NaN,1.0

In [4]:
liaison_select_rename.head(30)

,id,alumni_id,grad_year,dept,class,zh_name,cell,email,contact,birthday,liaison
0,1.0,AD05352108,53,會計,A,王小佗,0910128383,hsiaoto@gmail.com,15,NaN,1.0
1,2.0,AD05552122,55,會計,A,陳秀男,0979610770,willchen65@yahoo.com.tw,0,NaN,1.0
3,4.0,AD05921106,59,英文,不分班,曾文欽,0930756966,Charlestw@mail2000.com.tw,NaN,NaN,1.0
4,5.0,AD05941107,59,法律,A,洪長岸,0905516878,monty@highlink.com.tw(錯誤),26,1946/1/18,1.0
5,6.0,AD05952177,59,會計,A,蕭如意,0937894952,louis668@ms43.hinet.net,100,NaN,1.0
6,7.0,AD06011155,60,中文,A,顏秉直,(02)87737330,0931015@gmail.com,NaN,NaN,1.0
7,8.0,AD06014121,60,政治,不分班,林清水,NaN,NaN,10,NaN,1.0
8,9.0,AD06021111,60,英文,不分班,葉佐良,0958788130,martinyeh2354@yahoo.com.tw,19,1948/10/18,1.0
9,10.0,AD06021129,60,英文,不分班,蔡瑞容,‭0920350823‬,NaN,30,1949/2/9,1.0
10,11.0,AD06052211,60,會計,B,宋一新,0932080365,adam@gialens.com.tw,15,NaN,1.0
11,12.0,AD06114117,61,政治,不分班,趙慶華,0919821586,chaoch3840@gmail.com,28,NaN,1.0
12,13.0,AD06152135,61,會計,A,邵清榮,NaN,NaN,NaN,NaN,1.0
13,14.0,AD06152216,61,會計,B,周雙仁,0937048493,tony.chow@tcnco.com.tw,20,NaN,1.0
15,16.0,AD06252122,62,會計,A,陳永清,0932316366\n(02)23822756,cccpa0509@hotmail.com,32,1950/5/9,1.0
16,17.0,AD06253119,62,企管,不分班,李慧蘭,0912726066\n,liliannalee@gmail.com(錯誤),NaN,NaN,1.0
17,18.0,AD06314103,63,政治,不分班,唐銘崡,0935948676,serenatang5858@gmail.com,27,NaN,1.0
18,19.0,AD06333134,63,化學,不分班,陳泰興,0931130256,NaN,15,NaN,1.0
19,20.0,AD06352154,63,會計,A,王金山,0928098999,victorwang@deloitte.com.tw,35,NaN,1.0
20,21.0,AD06353126,63,企管,不分班,張聰達,...,monialan@ms29.hinet.net,NaN,NaN,1.0
21,22.0,AD06353130,63,企管,不分班,邱創鴻,0910159059,hongan1949@gmail.com,15,1949/3/16,1.0
22,23.0,AD06414104,64,政治,不分班,李素珍,0921861518,chuenchuenchang@gmail.com\nhilingos@ms19.hinet...,NaN,NaN,1.0
23,24.0,AD06421158,64,英文,不分班,李怡,0911287044,annalee@chmataiwan.org,NaN,NaN,1.0
24,25.0,AD06421258,64,英文,B,陳若玲,0928218908,annerl.chen@gmail.com,50,1953/8/12,1.0
26,27.0,AD06433116,64,化學,不分班,羅芬臺,0939151070,luoft@lfty.tw,13,NaN,1.0
27,28.0,AD06451143,64,經濟,A,方嘉男,0936263706,00104bop@bop.com.tw,30,1953/5/16,1.0
29,30.0,AD06452148,64,會計,A,董世慶,0912215605,euginetung@gmail.com,50,NaN,1.0
30,31.0,AD06453166,64,企管,不分班,周兒坤,0937194029,ekchou51@yahoo.com.tw,34,NaN,1.0
32,33.0,AD06455112,64,財精,A,莊聲和,0920411255,jsh@scu.edu.tw,NaN,1954/1/6,1.0
33,34.0,AD06455204,64,財精,B,顏宗明,0937537006,randyyen40@gmail.com,15,1951/11/14,1.0
34,35.0,AD06514121,65,政治,不分班,葉維銓,0937890768,j0937890768@gmail.com,40,NaN,1.0

In [5]:
liaison_clean=liaison_select_rename.replace('\n','',regex=True)
liaison_clean.head(30)

,id,alumni_id,grad_year,dept,class,zh_name,cell,email,contact,birthday,liaison
0,1.0,AD05352108,53,會計,A,王小佗,0910128383,hsiaoto@gmail.com,15,NaN,1.0
1,2.0,AD05552122,55,會計,A,陳秀男,0979610770,willchen65@yahoo.com.tw,0,NaN,1.0
3,4.0,AD05921106,59,英文,不分班,曾文欽,0930756966,Charlestw@mail2000.com.tw,NaN,NaN,1.0
4,5.0,AD05941107,59,法律,A,洪長岸,0905516878,monty@highlink.com.tw(錯誤),26,1946/1/18,1.0
5,6.0,AD05952177,59,會計,A,蕭如意,0937894952,louis668@ms43.hinet.net,100,NaN,1.0
6,7.0,AD06011155,60,中文,A,顏秉直,(02)87737330,0931015@gmail.com,NaN,NaN,1.0
7,8.0,AD06014121,60,政治,不分班,林清水,NaN,NaN,10,NaN,1.0
8,9.0,AD06021111,60,英文,不分班,葉佐良,0958788130,martinyeh2354@yahoo.com.tw,19,1948/10/18,1.0
9,10.0,AD06021129,60,英文,不分班,蔡瑞容,‭0920350823‬,NaN,30,1949/2/9,1.0
10,11.0,AD06052211,60,會計,B,宋一新,0932080365,adam@gialens.com.tw,15,NaN,1.0
11,12.0,AD06114117,61,政治,不分班,趙慶華,0919821586,chaoch3840@gmail.com,28,NaN,1.0
12,13.0,AD06152135,61,會計,A,邵清榮,NaN,NaN,NaN,NaN,1.0
13,14.0,AD06152216,61,會計,B,周雙仁,0937048493,tony.chow@tcnco.com.tw,20,NaN,1.0
15,16.0,AD06252122,62,會計,A,陳永清,0932316366(02)23822756,cccpa0509@hotmail.com,32,1950/5/9,1.0
16,17.0,AD06253119,62,企管,不分班,李慧蘭,0912726066,liliannalee@gmail.com(錯誤),NaN,NaN,1.0
17,18.0,AD06314103,63,政治,不分班,唐銘崡,0935948676,serenatang5858@gmail.com,27,NaN,1.0
18,19.0,AD06333134,63,化學,不分班,陳泰興,0931130256,NaN,15,NaN,1.0
19,20.0,AD06352154,63,會計,A,王金山,0928098999,victorwang@deloitte.com.tw,35,NaN,1.0
20,21.0,AD06353126,63,企管,不分班,張聰達,...,monialan@ms29.hinet.net,NaN,NaN,1.0
21,22.0,AD06353130,63,企管,不分班,邱創鴻,0910159059,hongan1949@gmail.com,15,1949/3/16,1.0
22,23.0,AD06414104,64,政治,不分班,李素珍,0921861518,chuenchuenchang@gmail.comhilingos@ms19.hinet.net,NaN,NaN,1.0
23,24.0,AD06421158,64,英文,不分班,李怡,0911287044,annalee@chmataiwan.org,NaN,NaN,1.0
24,25.0,AD06421258,64,英文,B,陳若玲,0928218908,annerl.chen@gmail.com,50,1953/8/12,1.0
26,27.0,AD06433116,64,化學,不分班,羅芬臺,0939151070,luoft@lfty.tw,13,NaN,1.0
27,28.0,AD06451143,64,經濟,A,方嘉男,0936263706,00104bop@bop.com.tw,30,1953/5/16,1.0
29,30.0,AD06452148,64,會計,A,董世慶,0912215605,euginetung@gmail.com,50,NaN,1.0
30,31.0,AD06453166,64,企管,不分班,周兒坤,0937194029,ekchou51@yahoo.com.tw,34,NaN,1.0
32,33.0,AD06455112,64,財精,A,莊聲和,0920411255,jsh@scu.edu.tw,NaN,1954/1/6,1.0
33,34.0,AD06455204,64,財精,B,顏宗明,0937537006,randyyen40@gmail.com,15,1951/11/14,1.0
34,35.0,AD06514121,65,政治,不分班,葉維銓,0937890768,j0937890768@gmail.com,40,NaN,1.0

In [6]:
liaison_replace=liaison_clean.replace('   ','0',regex=True)
liaison_replace[['contact']]=liaison_replace[['contact']].fillna(value=0)
liaison_replace.head()

,id,alumni_id,grad_year,dept,class,zh_name,cell,email,contact,birthday,liaison
0,1.0,AD05352108,53,會計,A,王小佗,0910128383,hsiaoto@gmail.com,15,NaN,1.0
1,2.0,AD05552122,55,會計,A,陳秀男,0979610770,willchen65@yahoo.com.tw,0,NaN,1.0
3,4.0,AD05921106,59,英文,不分班,曾文欽,0930756966,Charlestw@mail2000.com.tw,0,NaN,1.0
4,5.0,AD05941107,59,法律,A,洪長岸,0905516878,monty@highlink.com.tw(錯誤),26,1946/1/18,1.0
5,6.0,AD05952177,59,會計,A,蕭如意,0937894952,louis668@ms43.hinet.net,100,NaN,1.0

In [7]:
convert_dict={'grad_year':int,'liaison':int}
liaison_replace=liaison_replace.astype(convert_dict)
liaison_replace.head()

,id,alumni_id,grad_year,dept,class,zh_name,cell,email,contact,birthday,liaison
0,1.0,AD05352108,53,會計,A,王小佗,0910128383,hsiaoto@gmail.com,15,NaN,1
1,2.0,AD05552122,55,會計,A,陳秀男,0979610770,willchen65@yahoo.com.tw,0,NaN,1
3,4.0,AD05921106,59,英文,不分班,曾文欽,0930756966,Charlestw@mail2000.com.tw,0,NaN,1
4,5.0,AD05941107,59,法律,A,洪長岸,0905516878,monty@highlink.com.tw(錯誤),26,1946/1/18,1
5,6.0,AD05952177,59,會計,A,蕭如意,0937894952,louis668@ms43.hinet.net,100,NaN,1

In [8]:
liaison_replace[['grad_year']]=liaison_replace[['grad_year']]+1911
liaison_replace.head()

,id,alumni_id,grad_year,dept,class,zh_name,cell,email,contact,birthday,liaison
0,1.0,AD05352108,1964,會計,A,王小佗,0910128383,hsiaoto@gmail.com,15,NaN,1
1,2.0,AD05552122,1966,會計,A,陳秀男,0979610770,willchen65@yahoo.com.tw,0,NaN,1
3,4.0,AD05921106,1970,英文,不分班,曾文欽,0930756966,Charlestw@mail2000.com.tw,0,NaN,1
4,5.0,AD05941107,1970,法律,A,洪長岸,0905516878,monty@highlink.com.tw(錯誤),26,1946/1/18,1
5,6.0,AD05952177,1970,會計,A,蕭如意,0937894952,louis668@ms43.hinet.net,100,NaN,1

In [11]:
liaison_replace.head(20)

,id,alumni_id,grad_year,dept,class,zh_name,cell,email,contact,birthday,liaison
0,1.0,AD05352108,1964,會計,A,王小佗,0910128383,hsiaoto@gmail.com,15,NaN,1
1,2.0,AD05552122,1966,會計,A,陳秀男,0979610770,willchen65@yahoo.com.tw,0,NaN,1
3,4.0,AD05921106,1970,英文,不分班,曾文欽,0930756966,Charlestw@mail2000.com.tw,0,NaN,1
4,5.0,AD05941107,1970,法律,A,洪長岸,0905516878,monty@highlink.com.tw(錯誤),26,1946/1/18,1
5,6.0,AD05952177,1970,會計,A,蕭如意,0937894952,louis668@ms43.hinet.net,100,NaN,1
6,7.0,AD06011155,1971,中文,A,顏秉直,(02)87737330,0931015@gmail.com,0,NaN,1
7,8.0,AD06014121,1971,政治,不分班,林清水,NaN,NaN,10,NaN,1
8,9.0,AD06021111,1971,英文,不分班,葉佐良,0958788130,martinyeh2354@yahoo.com.tw,19,1948/10/18,1
9,10.0,AD06021129,1971,英文,不分班,蔡瑞容,‭0920350823‬,NaN,30,1949/2/9,1
10,11.0,AD06052211,1971,會計,B,宋一新,0932080365,adam@gialens.com.tw,15,NaN,1
11,12.0,AD06114117,1972,政治,不分班,趙慶華,0919821586,chaoch3840@gmail.com,28,NaN,1
12,13.0,AD06152135,1972,會計,A,邵清榮,NaN,NaN,0,NaN,1
13,14.0,AD06152216,1972,會計,B,周雙仁,0937048493,tony.chow@tcnco.com.tw,20,NaN,1
15,16.0,AD06252122,1973,會計,A,陳永清,0932316366(02)23822756,cccpa0509@hotmail.com,32,1950/5/9,1
16,17.0,AD06253119,1973,企管,不分班,李慧蘭,0912726066,liliannalee@gmail.com(錯誤),0,NaN,1
17,18.0,AD06314103,1974,政治,不分班,唐銘崡,0935948676,serenatang5858@gmail.com,27,NaN,1
18,19.0,AD06333134,1974,化學,不分班,陳泰興,0931130256,NaN,15,NaN,1
19,20.0,AD06352154,1974,會計,A,王金山,0928098999,victorwang@deloitte.com.tw,35,NaN,1
20,21.0,AD06353126,1974,企管,不分班,張聰達,0000000000000000000000,monialan@ms29.hinet.net,0,NaN,1
21,22.0,AD06353130,1974,企管,不分班,邱創鴻,0910159059,hongan1949@gmail.com,15,1949/3/16,1