In [1]:
# import numpy as np
import pandas as pd

table1=pd.read_csv("/Users/humphreyshen/Desktop/2021 Database Project/003數據預處理/2000筆植入ID/原始csv檔區/001-250.csv")
table1.head()

,作業編號,ID,畢業學系,年級,zh_name,en_name,gender,birthday,age,email,...,district,address,cell,tele,id_num,last_edit,bye,note,任職公司,重複
0,1,113435.0,資訊管理學系,108,巫沚臻,"WU, CHIH-CHEN",NaN,1997/03/03,NaN,joanwu11226@gmail.com,...,板橋區,新北市板橋區文聖街１８９號１４樓,987907091,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
1,2,107203.0,法律學系,106,蕭君鈴,"HSIAO, CHUN-LING",NaN,1984/03/31,NaN,courage0331@gmail.com,...,萬華區,台北市萬華區西園路２段９６巷３２號４樓,972929057,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
2,3,105797.0,經濟學系、108級企研所,106,黃奕豪,NaN,NaN,1994/10/08,NaN,derek831008@gmail.com,...,NaN,NaN,975306253,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
3,4,25768.0,85級經濟系研究所、83級經濟系,83,鄭淑穎,NaN,NaN,NaN,NaN,sweetjeng@itri.org.tw,...,東區光,新竹市東區光復路一段89巷159號6樓,981162089,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
4,5,85662.0,96級英文系 /98級EMBA/06級經濟系,96,魯亮君,NaN,1.0,1976/04/02,NaN,ryan.lu@moserbaer.net,...,龜山區,桃園市龜山區文二一街12號4樓之5,966996936,NaN,NaN,NaN,1,NaN,NaN,#ERROR!

In [2]:
table1_select=table1.loc[:,['ID','en_name','gender','birthday','age','email','zip_code','region','county','district','address','cell','tele','id_num']]
table1_select.head()

,ID,en_name,gender,birthday,age,email,zip_code,region,county,district,address,cell,tele,id_num
0,113435.0,"WU, CHIH-CHEN",NaN,1997/03/03,NaN,joanwu11226@gmail.com,220.0,TW,新北市,板橋區,新北市板橋區文聖街１８９號１４樓,987907091,NaN,NaN
1,107203.0,"HSIAO, CHUN-LING",NaN,1984/03/31,NaN,courage0331@gmail.com,108.0,TW,台北市,萬華區,台北市萬華區西園路２段９６巷３２號４樓,972929057,NaN,NaN
2,105797.0,NaN,NaN,1994/10/08,NaN,derek831008@gmail.com,NaN,NaN,NaN,NaN,NaN,975306253,NaN,NaN
3,25768.0,NaN,NaN,NaN,NaN,sweetjeng@itri.org.tw,300.0,TW,新竹市,東區光,新竹市東區光復路一段89巷159號6樓,981162089,NaN,NaN
4,85662.0,NaN,1.0,1976/04/02,NaN,ryan.lu@moserbaer.net,333.0,TW,桃園市,龜山區,桃園市龜山區文二一街12號4樓之5,966996936,NaN,NaN

In [3]:
table1_select_id=table1_select.dropna(subset=['ID'])
table1_select_id.head(20)

,ID,en_name,gender,birthday,age,email,zip_code,region,county,district,address,cell,tele,id_num
0,113435.0,"WU, CHIH-CHEN",NaN,1997/03/03,NaN,joanwu11226@gmail.com,220.0,TW,新北市,板橋區,新北市板橋區文聖街１８９號１４樓,987907091,NaN,NaN
1,107203.0,"HSIAO, CHUN-LING",NaN,1984/03/31,NaN,courage0331@gmail.com,108.0,TW,台北市,萬華區,台北市萬華區西園路２段９６巷３２號４樓,972929057,NaN,NaN
2,105797.0,NaN,NaN,1994/10/08,NaN,derek831008@gmail.com,NaN,NaN,NaN,NaN,NaN,975306253,NaN,NaN
3,25768.0,NaN,NaN,NaN,NaN,sweetjeng@itri.org.tw,300.0,TW,新竹市,東區光,新竹市東區光復路一段89巷159號6樓,981162089,NaN,NaN
4,85662.0,NaN,1.0,1976/04/02,NaN,ryan.lu@moserbaer.net,333.0,TW,桃園市,龜山區,桃園市龜山區文二一街12號4樓之5,966996936,NaN,NaN
5,84081.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,955029533,NaN,NaN
6,103913.0,NaN,0.0,1971/08/17,NaN,oli720128@gmail.com,NaN,NaN,NaN,NaN,NaN,963720128,NaN,Y220322483
7,3321.0,NaN,1.0,1972/01/01,NaN,jackyyu22@gmail.com,112.0,TW,台北市,北投區,台北市北投區東華街2段36號6樓,972820589,NaN,Y120339780
8,93935.0,NaN,1.0,1974/10/19,NaN,winchang2012@gmail.com,NaN,NaN,NaN,NaN,NaN,921963596,NaN,R120737085
9,117364.0,NaN,NaN,NaN,NaN,Melissa18528@yahoo.com.tw,105.0,TW,台北市,松山區,台北市松山區三民路72-2號5樓,909356839,NaN,NaN
11,103914.0,NaN,1.0,1972/03/10,NaN,calvin0939@gmail.com,NaN,NaN,NaN,NaN,NaN,939500169,NaN,A122394379
12,103911.0,NaN,0.0,1973/11/15,NaN,c646001@yahoo.com.tw,NaN,NaN,NaN,NaN,NaN,926646001,NaN,F222159868
13,114086.0,"LIN, I-CHU",NaN,1974/05/22,NaN,jumy.lin@yuanlibeauty.com.tw,235.0,TW,新北市,中和區,新北市中和區中正路６８３號２２樓之２,932156911,NaN,NaN
19,94051.0,NaN,NaN,NaN,NaN,tienyu689@gmail.com,NaN,NaN,NaN,NaN,NaN,988679966,NaN,NaN
21,100605.0,"TSENG, WEN-CHUN",NaN,1948/12/13,NaN,yuyuyu605@gmail.com,115.0,TW,台北市,南港區,台北市南港區中坡北路６０巷１號２樓,928841133,NaN,NaN
23,103546.0,NaN,0.0,NaN,NaN,nina510057tpe@yahoo.com.tw,NaN,NaN,NaN,NaN,NaN,922 51005,NaN,NaN
24,33439.0,NaN,NaN,NaN,NaN,kengo6586@hcjhs.ntpc.edu.tw,NaN,NaN,NaN,NaN,NaN,921895743,NaN,NaN
25,56635.0,NaN,NaN,NaN,NaN,penny4702086@yahoo.com.tw,NaN,NaN,NaN,NaN,NaN,939339641,NaN,NaN
27,72315.0,NaN,0.0,1955/09/30,NaN,diana_feng@mail2000.com.tw,NaN,NaN,NaN,NaN,NaN,932189157,NaN,L201095050
28,17966.0,NaN,1.0,1966/08/18,NaN,mytour.blue@gmail.com,105.0,TW,台北市,松山區,台北市松山區三民路130巷29號3樓,938395005,NaN,A120115996

In [8]:
table1_select_id.to_csv('001-250_clean.csv')

In [4]:
table1_select.head()

,ID,en_name,gender,birthday,age,email,zip_code,region,county,district,address,cell,tele,id_num
0,113435.0,"WU, CHIH-CHEN",NaN,1997/03/03,NaN,joanwu11226@gmail.com,220.0,TW,新北市,板橋區,新北市板橋區文聖街１８９號１４樓,987907091,NaN,NaN
1,107203.0,"HSIAO, CHUN-LING",NaN,1984/03/31,NaN,courage0331@gmail.com,108.0,TW,台北市,萬華區,台北市萬華區西園路２段９６巷３２號４樓,972929057,NaN,NaN
2,105797.0,NaN,NaN,1994/10/08,NaN,derek831008@gmail.com,NaN,NaN,NaN,NaN,NaN,975306253,NaN,NaN
3,25768.0,NaN,NaN,NaN,NaN,sweetjeng@itri.org.tw,300.0,TW,新竹市,東區光,新竹市東區光復路一段89巷159號6樓,981162089,NaN,NaN
4,85662.0,NaN,1.0,1976/04/02,NaN,ryan.lu@moserbaer.net,333.0,TW,桃園市,龜山區,桃園市龜山區文二一街12號4樓之5,966996936,NaN,NaN

In [5]:
table２_select=table1.loc[:,['ID','zh_name','en_name','gender','birthday','age','email','zip_code','region','county','district','address','cell','tele','id_num']]
table2_id_null_mask=table2_select['ID'].isnull()
table2_idisnull=table2_select[table2_id_null_mask]
table2_idisnull.head()

,ID,zh_name,en_name,gender,birthday,age,email,zip_code,region,county,district,address,cell,tele,id_num
10,NaN,黃昱銘,NaN,NaN,NaN,NaN,charis9106@gmail.com,NaN,NaN,NaN,NaN,NaN,933346668,NaN,NaN
14,NaN,梁淇涓,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,陳怡榛,NaN,0.0,1977/11/29,NaN,zsuyin1129@gmail.com,NaN,NaN,NaN,NaN,NaN,939071349,NaN,F223983573
16,NaN,黄美玲,NaN,NaN,NaN,NaN,marilyn@taifer.com.tw,NaN,NaN,NaN,NaN,NaN,928222218,NaN,NaN
17,NaN,李其曄,NaN,NaN,NaN,NaN,kiwi_lee@pj.com.tw,NaN,NaN,NaN,NaN,NaN,928295294,NaN,NaN

In [26]:
table2_idisnull.to_csv('001-250_idnull.csv')

In [6]:
table1

,作業編號,ID,畢業學系,年級,zh_name,en_name,gender,birthday,age,email,...,district,address,cell,tele,id_num,last_edit,bye,note,任職公司,重複
0,1,113435.0,資訊管理學系,108,巫沚臻,"WU, CHIH-CHEN",NaN,1997/03/03,NaN,joanwu11226@gmail.com,...,板橋區,新北市板橋區文聖街１８９號１４樓,987907091,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
1,2,107203.0,法律學系,106,蕭君鈴,"HSIAO, CHUN-LING",NaN,1984/03/31,NaN,courage0331@gmail.com,...,萬華區,台北市萬華區西園路２段９６巷３２號４樓,972929057,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
2,3,105797.0,經濟學系、108級企研所,106,黃奕豪,NaN,NaN,1994/10/08,NaN,derek831008@gmail.com,...,NaN,NaN,975306253,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
3,4,25768.0,85級經濟系研究所、83級經濟系,83,鄭淑穎,NaN,NaN,NaN,NaN,sweetjeng@itri.org.tw,...,東區光,新竹市東區光復路一段89巷159號6樓,981162089,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
4,5,85662.0,96級英文系 /98級EMBA/06級經濟系,96,魯亮君,NaN,1.0,1976/04/02,NaN,ryan.lu@moserbaer.net,...,龜山區,桃園市龜山區文二一街12號4樓之5,966996936,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,96748.0,日本語文學系,88,劉靜瑋,NaN,0.0,NaN,NaN,suzyliu22@gmail.com,...,桃園區,桃園市桃園區中山路775號11樓之3,953234553,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
246,247,84563.0,日本語文學系,103,吳怡逸,NaN,NaN,NaN,NaN,777666joywu@gmail.com,...,中和區,新北市中和區民安街25巷12弄9號3樓,937460425,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
247,248,NaN,日本語文學系,NaN,吳欣芳,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,976326910,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
248,249,67548.0,日本語文學系,102,張孝薇,NaN,NaN,NaN,NaN,shelly5024@hotmail.com,...,松山區,台北市松山區健康路185巷10-1號4樓,987390524,NaN,NaN,NaN,1,NaN,NaN,#ERROR!
249,250,106875.0,日本語文學系,106,陳奕廷,NaN,NaN,NaN,NaN,kannarutsuki820118@gmail.com,...,NaN,NaN,963425033,NaN,NaN,NaN,1,NaN,NaN,#ERROR!