In [3]:
import pandas as pd
import numpy as np

personal_pre=pd.read_csv('/Users/humphreyshen/Desktop/2021 Database Project/001總表最新資料/2021-12-27-updated_csv/dDt_alumnidb_personal_pre.csv')
personal_pre

,id,zh_name,en_name,gender,birthday,age,email,zip_code,region,county,district,address,cell,tele,id_num,last_edit,bye,note
0,1,殷葦婷,NaN,NaN,NaN,NaN,13816630288@163.con,20,CN,20,NaN,中國大陸上海市長寧區香花橋路38弄7號401室,NaN,13816630288,NaN,NaN,1,NaN
1,2,郭敬子,NaN,1.0,NaN,NaN,jimkuo49@gmail.com,200,TW,C,仁愛區,基隆市仁愛區愛七路53號3樓,918136219,NaN,NaN,NaN,1,NaN
2,3,陳仕俍,NaN,NaN,NaN,NaN,gelintex@ms27.hinet.net,205,TW,C,暖暖區,基隆市暖暖區暖碇路169號11樓,920521092,02-24573016,NaN,NaN,1,NaN
3,4,郭珈郗,NaN,NaN,NaN,NaN,grcekwk@gmail.com,NaN,HK,NaN,NaN,香港九龍官塘順安村安群樓514室,NaN,(+852)35929419,NaN,NaN,0,NaN
4,5,陸大文,NaN,1.0,1954-05-26,NaN,kathyhung168@gmail.com,105,TW,A,松山區,台北市松山區復興北路99號3樓,918511513,02-25478801,A101653944\r,NaN,1,important
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117819,117835,汪曼穎,NaN,0.0,NaN,NaN,未提供,NaN,NaN,NaN,NaN,NaN,未提供,NaN,NaN,0000-00-00 00:00:00.000000,1,important
117820,117836,侯佳彣,NaN,NaN,NaN,NaN,m1231@scu.edu.tw,NaN,NaN,NaN,NaN,NaN,921705820,NaN,NaN,0000-00-00 00:00:00.000000,1,important
117821,117837,廖永森,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,922207128,NaN,NaN,0000-00-00 00:00:00.000000,1,important
117822,117838,楊東霖,NaN,NaN,1992-08-12,NaN,tony2013168@gmail.com,NaN,NaN,NaN,NaN,NaN,938877811,NaN,NaN,0000-00-00 00:00:00.000000,1,important
117823,117839,吳欣芳,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,976326910,NaN,NaN,0000-00-00 00:00:00.000000,1,important

In [10]:
personal_final=personal_pre.loc[:,['id','zh_name','en_name','gender','birthday','age','email','zip_code','region','county','district','address','cell','tele','id_num','last_edit','bye','note']]
personal_cleaned=personal_final.replace({'\r':''},regex=True)
personal_cleaned

,id,zh_name,en_name,gender,birthday,age,email,zip_code,region,county,district,address,cell,tele,id_num,last_edit,bye,note
0,1,殷葦婷,NaN,NaN,NaN,NaN,13816630288@163.con,20,CN,20,NaN,中國大陸上海市長寧區香花橋路38弄7號401室,NaN,13816630288,NaN,NaN,1,NaN
1,2,郭敬子,NaN,1.0,NaN,NaN,jimkuo49@gmail.com,200,TW,C,仁愛區,基隆市仁愛區愛七路53號3樓,918136219,NaN,NaN,NaN,1,NaN
2,3,陳仕俍,NaN,NaN,NaN,NaN,gelintex@ms27.hinet.net,205,TW,C,暖暖區,基隆市暖暖區暖碇路169號11樓,920521092,02-24573016,NaN,NaN,1,NaN
3,4,郭珈郗,NaN,NaN,NaN,NaN,grcekwk@gmail.com,NaN,HK,NaN,NaN,香港九龍官塘順安村安群樓514室,NaN,(+852)35929419,NaN,NaN,0,NaN
4,5,陸大文,NaN,1.0,1954-05-26,NaN,kathyhung168@gmail.com,105,TW,A,松山區,台北市松山區復興北路99號3樓,918511513,02-25478801,A101653944,NaN,1,important
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117819,117835,汪曼穎,NaN,0.0,NaN,NaN,未提供,NaN,NaN,NaN,NaN,NaN,未提供,NaN,NaN,0000-00-00 00:00:00.000000,1,important
117820,117836,侯佳彣,NaN,NaN,NaN,NaN,m1231@scu.edu.tw,NaN,NaN,NaN,NaN,NaN,921705820,NaN,NaN,0000-00-00 00:00:00.000000,1,important
117821,117837,廖永森,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,922207128,NaN,NaN,0000-00-00 00:00:00.000000,1,important
117822,117838,楊東霖,NaN,NaN,1992-08-12,NaN,tony2013168@gmail.com,NaN,NaN,NaN,NaN,NaN,938877811,NaN,NaN,0000-00-00 00:00:00.000000,1,important
117823,117839,吳欣芳,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,976326910,NaN,NaN,0000-00-00 00:00:00.000000,1,important

In [11]:
personal_cleaned.to_csv('dDt_alumnidb_personal.csv',encoding='utf-8-sig')