In [1]:
import pandas as pd
import numpy as np

full_data=pd.read_csv('/Users/humphreyshen/Desktop/2021 Database Project/001總表下載數據/df_orginal_withoutblank.csv')
full_data.head(10)

/Users/humphreyshen/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (5,7,14) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,id,zh_name,en_name,gender,birthday,age,email,zip_code,region,county,district,address,cell,tele,id_num,last_edit,bye,note
0,1,殷葦婷,NaN,NaN,NaN,NaN,13816630288@163.con,20,CN,上海市,NaN,中國大陸上海市長寧區香花橋路38弄7號401室,NaN,13816630288,NaN,NaN,1,NULL\r
1,2,郭敬子,NaN,1.0,NaN,NaN,jimkuo49@gmail.com,200,TW,基隆市,仁愛區,基隆市仁愛區愛七路53號3樓,918136219,NaN,NaN,NaN,1,NULL\r
2,3,陳仕俍,NaN,NaN,NaN,NaN,gelintex@ms27.hinet.net,205,TW,基隆市,暖暖區,基隆市暖暖區暖碇路169號11樓,920521092,02-24573016,NaN,NaN,1,NULL\r
3,4,郭珈郗,NaN,NaN,NaN,NaN,grcekwk@gmail.com,NaN,HK,NaN,NaN,香港九龍官塘順安村安群樓514室,NaN,(+852)35929419,NaN,NaN,1,NULL\r
4,5,陸大文,NaN,1.0,1954/5/26,NaN,kathyhung168@gmail.com,105,TW,台北市,松山區,台北市松山區復興北路99號3樓,0918-032-920,02-25478801,A101653944,NaN,1,NULL\r
5,6,鄧淑珠,NaN,NaN,1962/5/10,NaN,terideng@scu.edu.tw,100,TW,台北市,中正區,台北市中正區貴陽街一段56號東吳大學會計辦公室,918868586,NaN,A221625395,NaN,1,NULL\r
6,7,黃歆桀,NaN,NaN,NaN,NaN,NaN,111,TW,台北市,士林區,台北市士林區天母西路13巷12號4樓,917164605,(02)2901-4361,NaN,NaN,1,NULL\r
7,8,劉?偉,NaN,1.0,1955/8/17,NaN,tonyrush54@hotmail.com,106,TW,台北市,大安區,台北市大安區光武里大安路1段19巷33號2樓,933573363,NaN,A111033365,NaN,1,NULL\r
8,9,林筠鳳,NaN,NaN,NaN,NaN,rosalin4547@gmail.com,235,TW,新北市,中和區,新北市中和區安樂路51巷36號3樓,919993171,NaN,NaN,NaN,1,NULL\r
9,10,吳明燁,NaN,NaN,NaN,NaN,mwu@scu.edu.tw,112,TW,台北市,北投區,台北市北投區奇岩里公館路165號9樓之1,930078802,NaN,NaN,NaN,1,NULL\r

In [2]:
ty_pre=full_data.loc[full_data.county=='桃園市',:]
ty_pre.head()

,id,zh_name,en_name,gender,birthday,age,email,zip_code,region,county,district,address,cell,tele,id_num,last_edit,bye,note
98,99,郭家安,NaN,NaN,NaN,NaN,NaN,338,TW,桃園市,蘆竹區,桃園市蘆竹區南福街63號2樓之2,NaN,NaN,NaN,NaN,1,NULL\r
114,115,趙逸翔,NaN,NaN,NaN,NaN,NaN,333,TW,桃園市,龜山區,桃園市龜山區南上路520巷6弄4號,NaN,NaN,NaN,NaN,1,NULL\r
120,121,李昀蓁,NaN,NaN,NaN,NaN,NaN,330,TW,桃園市,桃園區,桃園市桃園區桃園市桃園市復興路212號5F,NaN,NaN,NaN,NaN,1,NULL\r
121,122,周薇華,NaN,0.0,NaN,NaN,nydia921@gmail.com,338,TW,桃園市,蘆竹區,桃園市蘆竹區上竹村13鄰南竹路五段173號,983167080,NaN,NaN,NaN,1,NULL\r
122,123,林以涵,NaN,NaN,NaN,NaN,NaN,324,TW,桃園市,平鎮區,桃園市平鎮區平興里33鄰延平路二段430巷51號7樓,NaN,NaN,NaN,NaN,1,NULL\r

In [5]:
ty_pre.shape

(7005, 18)

In [11]:
ty_clean1=ty_pre.replace('\r','',regex=True)
ty_clean1.head(15)

,id,zh_name,en_name,gender,birthday,age,email,zip_code,region,county,district,address,cell,tele,id_num,last_edit,bye,note
98,99,郭家安,NaN,NaN,NaN,NaN,NaN,338,TW,桃園市,蘆竹區,桃園市蘆竹區南福街63號2樓之2,NaN,NaN,NaN,NaN,1,NULL
114,115,趙逸翔,NaN,NaN,NaN,NaN,NaN,333,TW,桃園市,龜山區,桃園市龜山區南上路520巷6弄4號,NaN,NaN,NaN,NaN,1,NULL
120,121,李昀蓁,NaN,NaN,NaN,NaN,NaN,330,TW,桃園市,桃園區,桃園市桃園區桃園市桃園市復興路212號5F,NaN,NaN,NaN,NaN,1,NULL
121,122,周薇華,NaN,0.0,NaN,NaN,nydia921@gmail.com,338,TW,桃園市,蘆竹區,桃園市蘆竹區上竹村13鄰南竹路五段173號,983167080,NaN,NaN,NaN,1,NULL
122,123,林以涵,NaN,NaN,NaN,NaN,NaN,324,TW,桃園市,平鎮區,桃園市平鎮區平興里33鄰延平路二段430巷51號7樓,NaN,NaN,NaN,NaN,1,NULL
132,133,吳宥融,NaN,NaN,NaN,NaN,NaN,320,TW,桃園市,中壢區,桃園市中壢區仁福里20鄰仁福五街14號3樓,NaN,NaN,NaN,NaN,1,NULL
177,178,軒漢,NaN,NaN,NaN,NaN,NaN,330,TW,桃園市,桃園區,桃園市桃園區桃園市桃園市莊敬路一段210巷之47號一樓,NaN,NaN,NaN,NaN,1,NULL
178,179,吳任容,NaN,NaN,NaN,NaN,NaN,330,TW,桃園市,桃園區,桃園市桃園區桃園市桃園市三民里3鄰鎮撫街160-5號6樓,NaN,NaN,NaN,NaN,1,NULL
179,180,潘冠諠,NaN,NaN,NaN,NaN,NaN,326,TW,桃園市,楊梅區,桃園市楊梅區瑞坪里22鄰梅獅路2段789巷18號,NaN,NaN,NaN,NaN,1,NULL
180,181,許瀚予,NaN,NaN,NaN,NaN,NaN,325,TW,桃園市,龍潭區,桃園市龍潭區桃園市龍潭區金龍路60巷182弄23號,NaN,NaN,NaN,NaN,1,NULL
191,192,游筱郁,NaN,NaN,NaN,NaN,NaN,320,TW,桃園市,中壢區,桃園市中壢區龍岡路1段239號,NaN,NaN,NaN,NaN,1,NULL
200,201,鄧佩瑜,NaN,NaN,NaN,NaN,NaN,320,TW,桃園市,中壢區,桃園市中壢區光明里20鄰中央西路二段135號,NaN,NaN,NaN,NaN,1,NULL
203,204,李怡靜,NaN,NaN,NaN,NaN,NaN,330,TW,桃園市,桃園區,桃園市桃園區玉山街275巷71之6號,NaN,NaN,NaN,NaN,1,NULL
230,231,張詩涵,NaN,NaN,NaN,NaN,NaN,334,TW,桃園市,八德區,桃園市八德區桃園市八德區廣福路125巷31號,NaN,NaN,NaN,NaN,1,NULL
231,232,鄭文瑄,NaN,NaN,NaN,NaN,NaN,330,TW,桃園市,桃園區,桃園市桃園區春日里21鄰大興路192巷14號3樓,NaN,NaN,NaN,NaN,1,NULL

In [17]:
ty_clean1.to_csv('Taoyuan_list.csv')